export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const LOG_IN = "LOG_IN";
export const REGISTER_USER = "REGISTER_USER";
export const DELETE_USER = "DELETE_USER";
export const USER_ERROR = "USER_ERROR";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";

export const FETCH_USER_STORIES = "FETCH_USER_STORIES";
export const CREATE_USER_STORY = "CREATE_USER_STORY";
export const EDIT_USER_STORY = "EDIT_USER_STORY";
export const DELETE_USER_STORY = "DELETE_USER_STORY";
export const FETCH_USER_DRAWINGS = "FETCH_USER_DRAWINGS";
export const CREATE_USER_DRAWING = "CREATE_USER_DRAWING";
export const EDIT_USER_DRAWING = "EDIT_USER_DRAWING";
export const DELETE_USER_DRAWING = "DELETE_USER_DRAWING";
//*************DONE */
export const FETCH_MOVIE_LOADING = "FETCH_MOVIE_LOADING";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_ERROR = "FETCH_MOVIE_ERROR";
